name: ganaderasoft_app_v1
description: "GanaderaSoft - Sistema de gesti√≥n integral para fincas ganaderas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.2
  path: ^1.8.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - lib/media/ganadera_logo_v1.png
    - assets/icon/app_icon_v1.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon_v1.png"